### ISSUE TITLE
what was the size of the model in CAQA or QAGen-T5

### ISSUE THREAD

**Issue by Soonhwan-Kwon** [Yueeeeeeee/CAQA#3]
Thank you for the great work.
While reading your paper, I can't find the hint of the model size of T5 what you used for CAQA/QAGen-T5.(t5-small, t5-base, t5-large, t5-3b, t5-11b) Would you be able to give us the model spec? 
Thank you in advance.

**Comment by Yueeeeeeee** [comment]
We used the t5-large model with default specs:)
