### ISSUE TITLE
T5 for extract QA

### ISSUE THREAD

**Issue by maxwellyin** [Yueeeeeeee/CAQA#6]
Hello,

I hope you're doing well. I came across your paper and noticed that you employ T5 to generate answers for an extractive QA task. I was wondering if you could kindly explain how you ensure that the generated answers are sourced from the given context.

Thank you for your time and assistance in addressing this question.

Best regards,
Maxwell.

**Comment by Yueeeeeeee** [comment]
Hi, T5 is tuned end-to-end so in most cases we find consisten answers in the context. In case where the generated answers are not in the context, we discard the generated QA pairs.

**Comment by maxwellyin** [comment]
Oh, get it. Thanks again for your help!
